-- 03) Sicurezza: RBAC + masking dati sensibili (GDPR)
-- Implementazione dei controlli di sicurezza:
-- - RBAC (Role Based Access Control)
-- - Masking dinamico dei dati sensibili (GDPR)
-- L'obiettivo è garantire accesso granulare ai dati clinici
-- e protezione dei dati personali

USE ROLE ACCOUNTADMIN;
USE DATABASE HEALTHDATAPRO_DB;

-- Creo ruoli applicativi distinti per separare le responsabilità
-- e limitare i privilegi secondo il principio del least privilege
CREATE OR REPLACE ROLE ROLE_DATA_ENGINEER;
CREATE OR REPLACE ROLE ROLE_DOCTOR;
CREATE OR REPLACE ROLE ROLE_NURSE;
CREATE OR REPLACE ROLE ROLE_ADMIN_STAFF;
CREATE OR REPLACE ROLE ROLE_ANALYST;

-- Grant minimi sui warehouse
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE ROLE_DATA_ENGINEER;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE ROLE_DOCTOR;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE ROLE_NURSE;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE ROLE_ADMIN_STAFF;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE ROLE_ANALYST;

-- Grant su database e schemi
GRANT USAGE ON DATABASE HEALTHDATAPRO_DB TO ROLE ROLE_DATA_ENGINEER;
GRANT USAGE ON DATABASE HEALTHDATAPRO_DB TO ROLE ROLE_DOCTOR;
GRANT USAGE ON DATABASE HEALTHDATAPRO_DB TO ROLE ROLE_NURSE;
GRANT USAGE ON DATABASE HEALTHDATAPRO_DB TO ROLE ROLE_ADMIN_STAFF;
GRANT USAGE ON DATABASE HEALTHDATAPRO_DB TO ROLE ROLE_ANALYST;

GRANT USAGE ON SCHEMA HEALTHDATAPRO_DB.CORE TO ROLE ROLE_DATA_ENGINEER;
GRANT USAGE ON SCHEMA HEALTHDATAPRO_DB.CORE TO ROLE ROLE_DOCTOR;
GRANT USAGE ON SCHEMA HEALTHDATAPRO_DB.CORE TO ROLE ROLE_NURSE;
GRANT USAGE ON SCHEMA HEALTHDATAPRO_DB.CORE TO ROLE ROLE_ADMIN_STAFF;

GRANT USAGE ON SCHEMA HEALTHDATAPRO_DB.ANALYTICS TO ROLE ROLE_ANALYST;
GRANT USAGE ON SCHEMA HEALTHDATAPRO_DB.ANALYTICS TO ROLE ROLE_DOCTOR;
GRANT USAGE ON SCHEMA HEALTHDATAPRO_DB.ANALYTICS TO ROLE ROLE_NURSE;
GRANT USAGE ON SCHEMA HEALTHDATAPRO_DB.ANALYTICS TO ROLE ROLE_ADMIN_STAFF;

-- Permessi sulle tabelle CORE
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA HEALTHDATAPRO_DB.CORE TO ROLE ROLE_DATA_ENGINEER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA HEALTHDATAPRO_DB.CORE TO ROLE ROLE_DATA_ENGINEER;

-- Medici / infermieri: lettura dati clinici
GRANT SELECT ON TABLE HEALTHDATAPRO_DB.CORE.PATIENTS    TO ROLE ROLE_DOCTOR;
GRANT SELECT ON TABLE HEALTHDATAPRO_DB.CORE.ENCOUNTERS  TO ROLE ROLE_DOCTOR;
GRANT SELECT ON TABLE HEALTHDATAPRO_DB.CORE.DIAGNOSES   TO ROLE ROLE_DOCTOR;
GRANT SELECT ON TABLE HEALTHDATAPRO_DB.CORE.PROCEDURES  TO ROLE ROLE_DOCTOR;
GRANT SELECT ON TABLE HEALTHDATAPRO_DB.CORE.LAB_RESULTS TO ROLE ROLE_DOCTOR;
GRANT SELECT ON TABLE HEALTHDATAPRO_DB.CORE.MEDICATIONS TO ROLE ROLE_DOCTOR;
GRANT SELECT ON TABLE HEALTHDATAPRO_DB.CORE.VITALS_IOT  TO ROLE ROLE_DOCTOR;

GRANT SELECT ON TABLE HEALTHDATAPRO_DB.CORE.PATIENTS    TO ROLE ROLE_NURSE;
GRANT SELECT ON TABLE HEALTHDATAPRO_DB.CORE.ENCOUNTERS  TO ROLE ROLE_NURSE;
GRANT SELECT ON TABLE HEALTHDATAPRO_DB.CORE.LAB_RESULTS TO ROLE ROLE_NURSE;
GRANT SELECT ON TABLE HEALTHDATAPRO_DB.CORE.MEDICATIONS TO ROLE ROLE_NURSE;
GRANT SELECT ON TABLE HEALTHDATAPRO_DB.CORE.VITALS_IOT  TO ROLE ROLE_NURSE;

-- Staff amministrativo: accesso “operativo” (senza dettagli clinici)
GRANT SELECT ON TABLE HEALTHDATAPRO_DB.CORE.ENCOUNTERS  TO ROLE ROLE_ADMIN_STAFF;
GRANT SELECT ON TABLE HEALTHDATAPRO_DB.CORE.DEPARTMENTS TO ROLE ROLE_ADMIN_STAFF;

-- L'analyst legge solo le viste analytics, ma serve anche SELECT sulle tabelle CORE usate dalle view
GRANT SELECT ON TABLE HEALTHDATAPRO_DB.CORE.ENCOUNTERS  TO ROLE ROLE_ANALYST;
GRANT SELECT ON TABLE HEALTHDATAPRO_DB.CORE.DEPARTMENTS TO ROLE ROLE_ANALYST;

-- Masking policy per GDPR (PII)
USE SCHEMA HEALTHDATAPRO_DB.SECURITY;

CREATE OR REPLACE MASKING POLICY MASK_PII AS (val STRING) RETURNS STRING ->
  CASE
    WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN', 'ROLE_DATA_ENGINEER', 'ROLE_DOCTOR') THEN val
    ELSE '***MASKED***'
  END;

-- Applichiamo la policy ai campi sensibili
ALTER TABLE HEALTHDATAPRO_DB.CORE.PATIENTS
  MODIFY COLUMN FISCAL_CODE SET MASKING POLICY MASK_PII;

ALTER TABLE HEALTHDATAPRO_DB.CORE.PATIENTS
  MODIFY COLUMN EMAIL SET MASKING POLICY MASK_PII;

ALTER TABLE HEALTHDATAPRO_DB.CORE.PATIENTS
  MODIFY COLUMN PHONE SET MASKING POLICY MASK_PII;

ALTER TABLE HEALTHDATAPRO_DB.CORE.PATIENTS
  MODIFY COLUMN ADDRESS SET MASKING POLICY MASK_PII;

-- Nome e cognome li mascheriamo per analisti/admin
ALTER TABLE HEALTHDATAPRO_DB.CORE.PATIENTS
  MODIFY COLUMN FIRST_NAME SET MASKING POLICY MASK_PII;

ALTER TABLE HEALTHDATAPRO_DB.CORE.PATIENTS
  MODIFY COLUMN LAST_NAME SET MASKING POLICY MASK_PII;