-- 04) Viste ANALYTICS per dashboard/report
-- Creazione di viste analitiche per dashboard e reporting
-- Le viste aggregano dati clinici per supportare
-- il monitoraggio delle performance ospedaliere

USE ROLE ACCOUNTADMIN;
USE DATABASE HEALTHDATAPRO_DB;
USE SCHEMA ANALYTICS;

-- Vista KPI: numero totale di ricoveri per reparto
CREATE OR REPLACE VIEW VW_ADMISSIONS_BY_DEPT AS
SELECT
  e.DEPARTMENT_ID,
  d.DEPARTMENT_NAME,
  COUNT(*) AS TOTAL_ENCOUNTERS
FROM CORE.ENCOUNTERS e
LEFT JOIN CORE.DEPARTMENTS d ON d.DEPARTMENT_ID = e.DEPARTMENT_ID
GROUP BY 1,2
ORDER BY TOTAL_ENCOUNTERS DESC;

-- Vista KPI: durata media del ricovero
CREATE OR REPLACE VIEW VW_AVG_LOS_HOURS_BY_DEPT AS
SELECT
  e.DEPARTMENT_ID,
  d.DEPARTMENT_NAME,
  AVG(DATEDIFF('hour', e.ADMIT_TS, e.DISCHARGE_TS)) AS AVG_LOS_HOURS
FROM CORE.ENCOUNTERS e
LEFT JOIN CORE.DEPARTMENTS d ON d.DEPARTMENT_ID = e.DEPARTMENT_ID
WHERE e.DISCHARGE_TS IS NOT NULL
GROUP BY 1,2
ORDER BY AVG_LOS_HOURS DESC;

-- Vista KPI: distribuzione outcome clinici per reparto.
CREATE OR REPLACE VIEW VW_OUTCOME_BY_DEPT AS
SELECT
  e.DEPARTMENT_ID,
  d.DEPARTMENT_NAME,
  e.OUTCOME,
  COUNT(*) AS TOTAL
FROM CORE.ENCOUNTERS e
LEFT JOIN CORE.DEPARTMENTS d ON d.DEPARTMENT_ID = e.DEPARTMENT_ID
GROUP BY 1,2,3
ORDER BY TOTAL DESC;

-- Permessi su viste per analyst (solo analytics)
GRANT SELECT ON ALL VIEWS IN SCHEMA HEALTHDATAPRO_DB.ANALYTICS TO ROLE ROLE_ANALYST;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA HEALTHDATAPRO_DB.ANALYTICS TO ROLE ROLE_ANALYST;

-- Permessi su viste per staff medico
GRANT SELECT ON ALL VIEWS IN SCHEMA HEALTHDATAPRO_DB.ANALYTICS TO ROLE ROLE_DOCTOR;
GRANT SELECT ON ALL VIEWS IN SCHEMA HEALTHDATAPRO_DB.ANALYTICS TO ROLE ROLE_NURSE;
GRANT SELECT ON ALL VIEWS IN SCHEMA HEALTHDATAPRO_DB.ANALYTICS TO ROLE ROLE_ADMIN_STAFF;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA HEALTHDATAPRO_DB.ANALYTICS TO ROLE ROLE_DOCTOR;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA HEALTHDATAPRO_DB.ANALYTICS TO ROLE ROLE_NURSE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA HEALTHDATAPRO_DB.ANALYTICS TO ROLE ROLE_ADMIN_STAFF;